/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\ascend-character.glb 
Author: EthanFromEngland (https://sketchfab.com/EthanfromEngland)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/collectible-cute-chibi-assassin-meshy-a6d72abafc124fabaa446a103f4b3a67
Title: Collectible Cute Chibi Assassin [MESHY]
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ascend-character.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Mesh_0_Material_0_0.geometry} material={materials.Material_0} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/ascend-character.glb')
